name: Build and deploy JAR app to Azure Web App - java104

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Checkout source code
      - uses: actions/checkout@v4

      # Setup Java (Maven build uses JDK 17)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      # Build JAR inside the server directory
      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: server

      # Upload the built JAR as an artifact
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: server/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # Download the JAR artifact from build job
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: server/target

      # Login to Azure with OIDC (no publish profile needed)
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy the JAR to Azure Web App
      - name: Deploy JAR to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'java104'          # 👈 your Azure Web App name
          slot-name: 'Production'
          package: server/target/*.jar # 👈 deploy the JAR
