name: UI - Build

on:
  push:
    branches: [ "main" ]
    paths:
      - "client/**"
      - ".github/workflows/ui-build.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Package artifact
        run: zip -r ../ui_release.zip build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui-build
          path: ui_release.zip
          retention-days: 7
